import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Providers} from "@/app/provider";
import {Header} from "@/components/Header";
import {Footer} from "@/components/Footer";
import {InteractiveBackground} from "@/components/InteractiveBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="de" className="dark">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-h-screen flex-col`}
        >
        <Providers>
            <InteractiveBackground /> {/* NEU: Hintergrund-Komponente hier platzieren */}
            <Header />
            {/* Der z-10 stellt sicher, dass der Inhalt über dem Hintergrund liegt */}
            <main className="flex-grow z-10">{children}</main>
            <Footer />
        </Providers>
        </body>
        </html>
    );

}