name: Deploy to VPS

on:
  push:
    branches: [ master ] # Löst bei jedem Push auf den 'master'-Branch aus

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Lade NVM explizit, damit npm und pm2 gefunden werden
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          
            # Führe die eigentlichen Deploy-Befehle aus
            cd /pfad/zu/deinem/projekt
            git pull origin main
            npm install --omit=dev
            npm run build
            pm2 restart meine-app